### ISSUE TITLE
Display issue on English device

### ISSUE THREAD

**Issue by recolic** [morrowind/HealthCode#2]
I'm using Android 11 (RP1A.200720.009), system language is English(United States). 

The app displays in English. Is it possible to force the app language to Chinese(China) ?

![screenshot](https://drive.recolic.cc/s/RRcPJHPyjABYLsC/download)

![screenshot2](https://drive.recolic.cc/s/yT6PiqoGD2BgCJE/download)

**Comment by morrowind** [comment]
> I'm using Android 11 (RP1A.200720.009), system language is English(United States).
> 
> The app displays in English. Is it possible to force the app language to Chinese(China) ?
>

Hi there,,, [I add a menu for manual select display language.](https://github.com/morrowind/HealthCode/commit/4132e1057823d5ee64fed94d0e8ac5d7e86c6c63)

**Comment by recolic** [comment]
Thanks a lot for that feature!
